### PR TITLE
fixed build on 6.5.9 on Opensuse Tumbleweed

### PR DESCRIPTION
**Pull request by OmegaDreamLord**
I had this issue where GCC gave this error when compiling the ashmem module: 

/var/lib/dkms/anbox-ashmem/1/build/ashmem.c:393:23: error: assignment of read-only member ‘vm_flags’

This has worked so far on my system and Waydroid starts and ashmem loads correctly.

### CODE REVIEW

File: ashmem/ashmem.c [hunk 1]
```diff
@@ -390,7 +390,8 @@ static int ashmem_mmap(struct file *file, struct vm_area_struct *vma)
 		ret = -EPERM;
 		goto out;
 	}
-	vma->vm_flags &= ~calc_vm_may_flags(~asma->prot_mask);
+	vma->vm_flags;
+	 ~calc_vm_may_flags(~asma->prot_mask);
```
Comment (choff) [inline ashmem/ashmem.c:394]: Well, this is not a correct patch - the code no longer does what it used to do (namely to remove some of the flags).
A slightly better patch is [available here](https://github.com/choff/anbox-modules/commit/18c81a56f885eea4a2fc1fe975761d4940315b4f) , but also this one is not correct because it just bypasses that the flags are read-only.

Proper patches are welcome, but this is a hack and not a proper fix. Therefore, I cannot merge it.

**Review by choff — CHANGES_REQUESTED** [review]

**Comment by choff** [comment]
Since you are using Waydroid: I think recent versions of Waydroid are no longer using ashmem. Maybe this is why you didn't see any errors after applying the patch..?

I think another possible solution could be to remove ashmem from anbox-modules.

**Comment by OmegaDreamLord** [comment]
Honestly I dont know why. I dont have any C knowledge or experience other than what google did, and what I did was a literal guess so Im shocked it did fix it, and Waydroid works absolutely fine with this so I'm not sure. Waydroid wouldn't start unless ashmem was loaded so thats why I did this. Its really strange and I think this is something that should be looked more into.. Cause Im honestly curious. This is the first time I've had problems with these, mainly bc I usually use Arch which has these modules in the zen kernel.

**Comment by OmegaDreamLord** [comment]
Also I tried a liquorix kernel for Opensuse and it didnt work properly for me but worked fine with the Opensuse default kernel for tumbleweed.. maybe this works just fine in newer kernels but I find it odd this happened. I also just looked at the patch and Im sure it is better so I'll have to try it and see how it runs. Thanks for looking into this! It was interesting of a ride.
